adding classes which are generally used in devmode to avoid NoClassDefFoundError in tests
git-svn-id: https://svn.terracotta.org/repo/tc/dso/trunk@22712 7fc7bbf3-cf45-46d4-be06-341739edd864